{{- if .Values.server.zt.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-server-identity-secret
type: Opaque
data:
  zid: {{ .Values.server.zt.id.contents | b64enc  }}
{{- end }}
