{{- if .Values.server.zt.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: configmap-reloadz-identity-secret
type: Opaque
data:
  zid: {{ .Values.configmapReload.zt.id.contents | b64enc }}
{{- end }}