{{- if .Values.alertmanager.ztfied -}}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-configmap-reloadz-zt-identity
type: Opaque
data:
  identityFileName: {{ .Values.alertmanager.zt.id | b64enc  }}
{{- end }}