apiVersion: v2
appVersion: 1.7.13
description: Dial Hanzo ZT services with a tunneler daemonset
kubeVersion: '>= 1.20.0-0'
name: ziti-edge-tunnel
type: application
version: 1.3.0
icon: https://hanzozt.dev/img/ziti-logo-dark.svg
sources:
- https://github.com/hanzozt/ziti-tunnel-sdk-c
keywords:
- hanzozt
- coredns
- node-local-dns
