{{- if not .Values.secret.existingSecretName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zt-edge-tunnel.fullname" . }}-identity-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
{{- end }}
