
# minimal input values for traefik ingress; to enable tls, add cert manager issuer annotation and tls.secretName to each ingress dict

controller:
  ingress:
    enabled: true
    scheme: http
    className: traefik
    # annotations:
    #   cert-manager.io/cluster-issuer: cloudflare-dns-issuer-prod
    # tls:
    #   secretName: zrok-api-tls

frontend:
  ingress:
    enabled: true
    scheme: http
    className: traefik
    # annotations:
    #   cert-manager.io/cluster-issuer: cloudflare-dns-issuer-prod
    # tls:
    #   secretName: zrok-wildcard-tls
