name: Bump Changed Charts' Versions
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  chart-version-checker:
    strategy:
      matrix:
        charts:
          - hello-toy
          - httpbin
          - reflect
          - zt-controller
          - zt-edge-tunnel
          - zt-host
          - zt-router
          - zrok
          - zt-browzer-bootstrapper
    runs-on: ubuntu-latest
    steps:
      - name: Bump Chart Versions if Changed
        id: bumper
        uses: netfoundry/chart-version-bumper-action@main
        with:
          chart_dir: ./charts/${{ matrix.charts }}

# grant write permission to GITHUB_TOKEN for version bumper to push commits to current branch
permissions:
  contents: write
